# Generated by Django 3.2.16 on 2022-10-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20221026_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name1',
            new_name='name',
        ),
    ]
