# Generated by Django 3.2.16 on 2022-10-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_auto_20221026_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='descr',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='image',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='namee',
            new_name='name1',
        ),
    ]
