# Generated by Django 3.2.16 on 2022-10-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_auto_20221026_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='people',
            new_name='team',
        ),
    ]
